/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RitualsRouteImport } from './routes/rituals'
import { Route as RashiRouteImport } from './routes/rashi'
import { Route as RakhiRouteImport } from './routes/rakhi'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as FindYourBraceletRouteImport } from './routes/find-your-bracelet'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RakhiSacredRouteImport } from './routes/rakhi.sacred'
import { Route as RakhiRashiRouteImport } from './routes/rakhi.rashi'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as RakhiRashiSlugRouteImport } from './routes/rakhi.rashi.$slug'
import { Route as RakhiProductSlugRouteImport } from './routes/rakhi.product.$slug'

const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RitualsRoute = RitualsRouteImport.update({
  id: '/rituals',
  path: '/rituals',
  getParentRoute: () => rootRouteImport,
} as any)
const RashiRoute = RashiRouteImport.update({
  id: '/rashi',
  path: '/rashi',
  getParentRoute: () => rootRouteImport,
} as any)
const RakhiRoute = RakhiRouteImport.update({
  id: '/rakhi',
  path: '/rakhi',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FindYourBraceletRoute = FindYourBraceletRouteImport.update({
  id: '/find-your-bracelet',
  path: '/find-your-bracelet',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RakhiSacredRoute = RakhiSacredRouteImport.update({
  id: '/sacred',
  path: '/sacred',
  getParentRoute: () => RakhiRoute,
} as any)
const RakhiRashiRoute = RakhiRashiRouteImport.update({
  id: '/rashi',
  path: '/rashi',
  getParentRoute: () => RakhiRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionsRoute,
} as any)
const RakhiRashiSlugRoute = RakhiRashiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RakhiRashiRoute,
} as any)
const RakhiProductSlugRoute = RakhiProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => RakhiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/find-your-bracelet': typeof FindYourBraceletRoute
  '/journal': typeof JournalRoute
  '/rakhi': typeof RakhiRouteWithChildren
  '/rashi': typeof RashiRoute
  '/rituals': typeof RitualsRoute
  '/search': typeof SearchRoute
  '/track-order': typeof TrackOrderRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/rakhi/rashi': typeof RakhiRashiRouteWithChildren
  '/rakhi/sacred': typeof RakhiSacredRoute
  '/rakhi/product/$slug': typeof RakhiProductSlugRoute
  '/rakhi/rashi/$slug': typeof RakhiRashiSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/find-your-bracelet': typeof FindYourBraceletRoute
  '/journal': typeof JournalRoute
  '/rakhi': typeof RakhiRouteWithChildren
  '/rashi': typeof RashiRoute
  '/rituals': typeof RitualsRoute
  '/search': typeof SearchRoute
  '/track-order': typeof TrackOrderRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/rakhi/rashi': typeof RakhiRashiRouteWithChildren
  '/rakhi/sacred': typeof RakhiSacredRoute
  '/rakhi/product/$slug': typeof RakhiProductSlugRoute
  '/rakhi/rashi/$slug': typeof RakhiRashiSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/find-your-bracelet': typeof FindYourBraceletRoute
  '/journal': typeof JournalRoute
  '/rakhi': typeof RakhiRouteWithChildren
  '/rashi': typeof RashiRoute
  '/rituals': typeof RitualsRoute
  '/search': typeof SearchRoute
  '/track-order': typeof TrackOrderRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/rakhi/rashi': typeof RakhiRashiRouteWithChildren
  '/rakhi/sacred': typeof RakhiSacredRoute
  '/rakhi/product/$slug': typeof RakhiProductSlugRoute
  '/rakhi/rashi/$slug': typeof RakhiRashiSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/find-your-bracelet'
    | '/journal'
    | '/rakhi'
    | '/rashi'
    | '/rituals'
    | '/search'
    | '/track-order'
    | '/collections/$slug'
    | '/products/$slug'
    | '/rakhi/rashi'
    | '/rakhi/sacred'
    | '/rakhi/product/$slug'
    | '/rakhi/rashi/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/find-your-bracelet'
    | '/journal'
    | '/rakhi'
    | '/rashi'
    | '/rituals'
    | '/search'
    | '/track-order'
    | '/collections/$slug'
    | '/products/$slug'
    | '/rakhi/rashi'
    | '/rakhi/sacred'
    | '/rakhi/product/$slug'
    | '/rakhi/rashi/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/find-your-bracelet'
    | '/journal'
    | '/rakhi'
    | '/rashi'
    | '/rituals'
    | '/search'
    | '/track-order'
    | '/collections/$slug'
    | '/products/$slug'
    | '/rakhi/rashi'
    | '/rakhi/sacred'
    | '/rakhi/product/$slug'
    | '/rakhi/rashi/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ContactRoute: typeof ContactRoute
  FindYourBraceletRoute: typeof FindYourBraceletRoute
  JournalRoute: typeof JournalRoute
  RakhiRoute: typeof RakhiRouteWithChildren
  RashiRoute: typeof RashiRoute
  RitualsRoute: typeof RitualsRoute
  SearchRoute: typeof SearchRoute
  TrackOrderRoute: typeof TrackOrderRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rituals': {
      id: '/rituals'
      path: '/rituals'
      fullPath: '/rituals'
      preLoaderRoute: typeof RitualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rashi': {
      id: '/rashi'
      path: '/rashi'
      fullPath: '/rashi'
      preLoaderRoute: typeof RashiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rakhi': {
      id: '/rakhi'
      path: '/rakhi'
      fullPath: '/rakhi'
      preLoaderRoute: typeof RakhiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-your-bracelet': {
      id: '/find-your-bracelet'
      path: '/find-your-bracelet'
      fullPath: '/find-your-bracelet'
      preLoaderRoute: typeof FindYourBraceletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rakhi/sacred': {
      id: '/rakhi/sacred'
      path: '/sacred'
      fullPath: '/rakhi/sacred'
      preLoaderRoute: typeof RakhiSacredRouteImport
      parentRoute: typeof RakhiRoute
    }
    '/rakhi/rashi': {
      id: '/rakhi/rashi'
      path: '/rashi'
      fullPath: '/rakhi/rashi'
      preLoaderRoute: typeof RakhiRashiRouteImport
      parentRoute: typeof RakhiRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/rakhi/rashi/$slug': {
      id: '/rakhi/rashi/$slug'
      path: '/$slug'
      fullPath: '/rakhi/rashi/$slug'
      preLoaderRoute: typeof RakhiRashiSlugRouteImport
      parentRoute: typeof RakhiRashiRoute
    }
    '/rakhi/product/$slug': {
      id: '/rakhi/product/$slug'
      path: '/product/$slug'
      fullPath: '/rakhi/product/$slug'
      preLoaderRoute: typeof RakhiProductSlugRouteImport
      parentRoute: typeof RakhiRoute
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsSlugRoute: typeof CollectionsSlugRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsSlugRoute: CollectionsSlugRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface RakhiRashiRouteChildren {
  RakhiRashiSlugRoute: typeof RakhiRashiSlugRoute
}

const RakhiRashiRouteChildren: RakhiRashiRouteChildren = {
  RakhiRashiSlugRoute: RakhiRashiSlugRoute,
}

const RakhiRashiRouteWithChildren = RakhiRashiRoute._addFileChildren(
  RakhiRashiRouteChildren,
)

interface RakhiRouteChildren {
  RakhiRashiRoute: typeof RakhiRashiRouteWithChildren
  RakhiSacredRoute: typeof RakhiSacredRoute
  RakhiProductSlugRoute: typeof RakhiProductSlugRoute
}

const RakhiRouteChildren: RakhiRouteChildren = {
  RakhiRashiRoute: RakhiRashiRouteWithChildren,
  RakhiSacredRoute: RakhiSacredRoute,
  RakhiProductSlugRoute: RakhiProductSlugRoute,
}

const RakhiRouteWithChildren = RakhiRoute._addFileChildren(RakhiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ContactRoute: ContactRoute,
  FindYourBraceletRoute: FindYourBraceletRoute,
  JournalRoute: JournalRoute,
  RakhiRoute: RakhiRouteWithChildren,
  RashiRoute: RashiRoute,
  RitualsRoute: RitualsRoute,
  SearchRoute: SearchRoute,
  TrackOrderRoute: TrackOrderRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
